In [8]:
from tensorflow.keras.preprocessing.text import one_hot 



In [10]:
sent=[ 
    'the glass of milk', 
    'the glass of juice', 
    'the cup of tea',
    'I am a good boy', 
    'I am a good developer', 
    'understand the meaning of words', 
    'your videos are good',]
 
voc_size=10000 
one_hot_repr=[one_hot(words,voc_size)for words in sent] 
one_hot_repr

[[7706, 8812, 9700, 1243],
 [7706, 8812, 9700, 8200],
 [7706, 3273, 9700, 514],
 [6800, 7256, 6980, 437, 2102],
 [6800, 7256, 6980, 437, 4342],
 [8254, 7706, 767, 9700, 1595],
 [8969, 3017, 6006, 437]]

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7706 8812 9700 1243]
 [   0    0    0    0 7706 8812 9700 8200]
 [   0    0    0    0 7706 3273 9700  514]
 [   0    0    0 6800 7256 6980  437 2102]
 [   0    0    0 6800 7256 6980  437 4342]
 [   0    0    0 8254 7706  767 9700 1595]
 [   0    0    0    0 8969 3017 6006  437]]


In [14]:
## feature representation
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs)